### PR TITLE
support building on more platforms

### PR DESCRIPTION
**Pull request by jcgruenhage**
This adds support for building on a lot more linux platforms. Supported
architectures now include x86_64, i686, powerpc64le and
aarch64. In addition to that, this adds the ability to use musl on each
of these as well, in addition to glibc.

### CODE REVIEW

**Comment by jcgruenhage** [comment]
cc @q66

**Comment by q66** [comment]
lgtm, also works for me (tested element 1.8.4, electron 13.x, ppc64le-musl)

**Comment by dbkr** [comment]
closing & re-opening to try & wake the linter job up...

**Review by dbkr — COMMENTED** [review]
Looks ok. If this gets much more complex it's probably going to need something a bit more sophisticated than just this file.

Bit weird that these effectively do nothing & have to be enabled by editing the code. Main issue here is that we have no means of maintaining this as we wouldn't be building for these platforms. Perhaps we could assign a maintainer for some 'community maintained' platforms?

**Comment by jcgruenhage** [comment]
I could be assigned as community maintainer for i686, x86_64 and aarch64, maybe @q66 could do ppc64?

**Comment by q66** [comment]
there is a bunch more stuff needed to get things built on ppc64le, but this part is the only one that's in element itself (the rest is workarounds for electron-builder, so that's a different upstream to address)

I test things fairly regularly, so this should be no problem

**Comment by jcgruenhage** [comment]
@dbkr anything that's needed to move this forward?

**Comment by dbkr** [comment]
I asked the team about this and the conclusion is that this seems fine. Currently the only 'dead' target in this file is x86 windows (which we previously built but don't anymore) so if we could just add some comments to explain why these targets are sitting around in the file without being enabled, that would be good (and add the semicolons that the linter wants).

**Comment by t3chguy** [comment]
> Currently the only 'dead' target in this file is x86 windows (which we previously built but don't anymore) 

I have plans to resurrect it

https://github.com/vector-im/element-web/issues/13175

**Comment by jcgruenhage** [comment]
I was under the impression that this bit of code was moved into `element-desktop` itself, which previously was holding a ts->js transpiled artefact, see https://github.com/vector-im/element-desktop/blob/develop/scripts/hak/target.ts. In which of these two places is the code maintained now?

**Comment by dbkr** [comment]
Good point - we should update both if we're changing it, possibly making builder refer to version in element-desktop

**Comment by t3chguy** [comment]
https://github.com/vector-im/element-builder/pull/67 makes the reference happen, please move these changes to element-desktop in their entirety where they'll be accepted with open arms!
All the target specs will live in element-desktop, element-builder will have the list of "ENABLED_TARGETS" (now just `targets` in index.ts)

**Pull request closed without merging**
